"""Render RESULTS.md from the pipeline's outputs. Numbers only enter the
document from this module, so the markdown can never drift from the code."""
from __future__ import annotations

from datetime import date

import pandas as pd

from . import config
from .attribution import LEVERS


def _md_table(df: pd.DataFrame, floatfmt: str = "{:,.1f}") -> str:
    cols = list(df.columns)
    lines = ["| " + " | ".join(str(c) for c in cols) + " |", "|" + "|".join("---" for _ in cols) + "|"]
    for _, row in df.iterrows():
        cells = []
        for c in cols:
            v = row[c]
            cells.append(floatfmt.format(v) if isinstance(v, float) else str(v))
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


def render(results: dict) -> str:
    m = results["model_report"]
    a = results["attribution_validation"]
    p = results["policy_report"]
    d = results["drift"]
    v = results["value_table"]

    models_df = pd.DataFrame(
        [{"Model": name.replace("_", " "), "MAE (kg)": f"{r['mae']:.1f}", "RMSE (kg)": f"{r['rmse']:.1f}", "R²": f"{r['r2']:.3f}"}
         for name, r in m["models"].items() if r is not None]
    )
    gbm, ridge, floor = m["models"]["gradient_boosting"], m["models"]["ridge_baseline"], m["models"]["noise_floor"]
    achievable = (ridge["mae"] - gbm["mae"]) / max(ridge["mae"] - floor["mae"], 1e-9)

    seg = pd.DataFrame(m["segments"])[["segment_key", "segment", "n", "mae", "rmse", "r2"]].copy()
    seg["mae"], seg["rmse"], seg["r2"] = seg["mae"].map("{:.1f}".format), seg["rmse"].map("{:.1f}".format), seg["r2"].map("{:.3f}".format)
    seg.columns = ["Segment key", "Segment", "n", "MAE (kg)", "RMSE (kg)", "R²"]

    imp = m["importance"].copy()
    imp.columns = ["Feature", "Permutation importance (MAE increase, kg)"]

    lever_rows = []
    for lever in LEVERS:
        r = a["per_lever"][lever]
        lever_rows.append({"Lever": config.LEVER_LABELS[lever], "True mean (kg)": r["true_mean_kg"],
                           "Estimated mean (kg)": r["estimated_mean_kg"], "Correlation": r["correlation"]})
    lever_df = pd.DataFrame(lever_rows)

    pol_rows = []
    for name, s in p["policies"].items():
        pol_rows.append({
            "Ranking policy": name.replace("_", " "),
            "Capture of controllable fuel": f"{s['capture_of_controllable_fuel']:.1%}",
            "Precision (actionable)": f"{s['precision_actionable']:.1%}",
            "Mean true controllable (kg)": s["mean_true_controllable_kg"],
            "Contextual share of reviewed excess": f"{s['contextual_share_of_reviewed_excess']:.1%}",
        })
    pol_df = pd.DataFrame(pol_rows)

    drift_sections = []
    for name, rep in d.items():
        flagged = rep[rep["flag"] != "OK"]
        max_feature_psi = rep.loc[rep["monitor"] == "feature", "value"].max()
        concept_z = rep.loc[rep["monitor"] == "concept", "value"].iloc[0]
        footer = f"*max feature PSI {max_feature_psi:.3f}; residual shift z = {concept_z:+.1f}*"
        summary = "All monitors OK." if flagged.empty else _md_table(flagged.assign(value=flagged["value"].round(3)), "{:,.3f}")
        drift_sections.append(f"**{name}**\n\n{summary}\n\n{footer}")

    val = v[["scenario", "prioritised_share", "adoption_rate", "realisation_rate", "avg_controllable_kg",
             "fuel_saved_kg", "net_value_aed"]].copy()
    val.columns = ["Scenario", "Prioritised share", "Adoption", "Realisation", "Avg controllable (kg)",
                   "Fuel saved (kg / yr)", "Net value (AED / yr)"]
    for c in ["Fuel saved (kg / yr)", "Net value (AED / yr)"]:
        val[c] = val[c].map(lambda x: f"{x:,.0f}")
    for c in ["Prioritised share", "Adoption", "Realisation"]:
        val[c] = val[c].map(lambda x: f"{x:.0%}")

    status = ", ".join(f"{k}: {n:,}" for k, n in p["status_counts"].items())
    lever_mix = ", ".join(f"{config.LEVER_LABELS[k]} {v:.0%}" for k, v in p["dominant_lever_mix_in_queue"].items())

    return f"""# Results — simulator benchmark

*Generated by `python -m fuelops` on {date.today().isoformat()} (seed {config.SEED}).
Every number below comes from the disclosed simulator in `fuelops/synthetic_data.py`.
None of it describes a real airline; it describes whether the method holds up.*

**Data:** {results['n_flights']:,} synthetic flights over 24 months.
**Split:** temporal — train {m['train_window'][0]} → {m['train_window'][1]} ({m['n_train']:,} flights, of which the last 20% calibrate the prediction interval), test {m['test_window'][0]} → {m['test_window'][1]} ({m['n_test']:,} flights).

## 1. Model vs baselines (held-out window)

{_md_table(models_df, "{:,.3f}")}

The noise floor is a model that predicts the simulator's signal exactly and is wrong only by the injected noise: no model can beat it. Gradient boosting closes **{achievable:.0%}** of the gap between the linear baseline and that floor. The remaining gap is the honest measure of what the model has not learned.

## 2. Prediction intervals

| | Coverage |
|---|---|
| Nominal | {m['interval']['nominal_coverage']:.0%} |
| Raw quantile models | {m['interval']['raw_coverage']:.1%} |
| After split-conformal calibration | {m['interval']['calibrated_coverage']:.1%} |

Conformal margin {m['interval']['conformal_margin_kg']:.0f} kg; mean calibrated interval width {m['interval']['mean_width_kg']:.0f} kg. Raw quantile models under-cover on a later time window, which is exactly why the interval is calibrated on held-out data before it is allowed to gate decisions.

## 3. Performance by segment

{_md_table(seg, "{:,.2f}")}

## 4. Permutation importance (structure check)

The data-generating process is disclosed, so this table cannot "discover" anything. It checks that the model recovered the structure it was given: sector length and the routing, taxi and cruise levers should dominate; month should be near zero because season enters through temperature and wind.

{_md_table(imp, "{:,.1f}")}

## 5. Counterfactual attribution vs ground truth

Controllable excess is estimated as *f(x) − f(x at benchmark operations)* and split across levers with exact Shapley values. Because the simulator's true split is known, the estimate can be scored:

| Check | Value |
|---|---|
| Correlation with true controllable kg | {a['controllable_correlation']:.3f} |
| MAE of controllable estimate | {a['controllable_mae_kg']:.0f} kg |
| True controllable share of excess | {a['true_controllable_share']:.1%} |
| Estimated controllable share | {a['estimated_controllable_share']:.1%} ({a['share_gap_pp']:+.1f} pp) |
| Dominant lever identified correctly | {a['dominant_lever_accuracy']:.1%} |

{_md_table(lever_df, "{:,.2f}")}

The estimate is systematically **conservative**: tree ensembles extrapolate flatly at the benchmark edge of the training distribution, so the counterfactual under-states the controllable component by a few points. The direction and size of that bias are known here; in production they would not be, which is the argument for validating attribution on a designed pilot rather than trusting it.

## 6. Decision policy — same review capacity, different lists

Top {p['k_fraction']:.0%} of the held-out window ({p['k']:,} flights) under four ranking policies:

{_md_table(pol_df, "{:,.0f}")}

Ranking on the total prediction — the obvious policy — sends operators to flights whose excess is mostly weather, payload and sector length. Ranking on attributed controllable excess reaches **{p['policies']['controllable_attribution']['capture_of_controllable_fuel'] / p['policies']['oracle_true_controllable']['capture_of_controllable_fuel']:.0%}** of the oracle's capture with **{p['policies']['controllable_attribution']['precision_actionable']:.0%}** actionable precision.

Queue status on the window — {status}. Abstention rate {p['abstention_rate']:.1%} (in-distribution data; abstention exists for the day the data is not). Dominant levers in the queue: {lever_mix}.

## 7. Drift monitoring — three windows, three signatures

Reference = season-matched training flights. Thresholds: PSI ≥ {config.PSI_WATCH_THRESHOLD} WATCH, ≥ {config.PSI_REVIEW_THRESHOLD} REVIEW; residual shift |z| ≥ {config.RESIDUAL_SHIFT_Z_THRESHOLD:.0f} REVIEW.

{(chr(10) * 2).join(drift_sections)}

Measurement drift (a data-feed definition change) barely registers on feature PSI and is caught by the residual monitor; operational drift (the world changed) is loud on feature PSI while residuals stay quiet because the model is still right. A monitoring design that only watches inputs would miss the first; one that only watches errors would be late on the second.

## 8. Value model (illustrative)

{_md_table(val)}

The pipeline-informed row replaces guessed inputs with the queue the decision engine actually produced. Everything else — adoption, realisation, fuel price — is an operating assumption, and the spread between rows is the point: the model's contribution ends at "prioritised".

## How to read this page

* These are simulator results. They say nothing about any airline's fuel performance.
* The simulator is disclosed in full and the same code is used to validate the method; that is its purpose.
* The right questions for a real deployment are in `MODEL_CARD.md` §10 and `FAILURE_ANALYSIS.md`.
"""


def write(results: dict, path=config.RESULTS_MD) -> None:
    path.write_text(render(results), encoding="utf-8")
